apiVersion: v1alpha1
kind: AgentConfig
metadata:
  name: ocp01
rendezvousIP: 10.226.224.35
additionalNTPSources:
- 0-6.ntp.pln.spirenteng.com
hosts:
  - hostname: master01.ocp01.pln.spirenteng.com
    role: master
    rootDeviceHints:
      deviceName: "/dev/sda"
    interfaces:
      - name: ens5f1
        macAddress: "3C:FD:FE:E1:47:2D"
    networkConfig:
      interfaces:
        - name: ens5f1
          type: ethernet
          state: up
          mac-address: "3C:FD:FE:E1:47:2D"
          ipv4:
            enabled: true
            address:
              - ip: 10.226.224.34
                prefix-length: 22
            dhcp: false
          ipv6: 
            enabled: true
            dhcp: true
      dns-resolver:
        config:
          server:
            - 10.226.255.5
            - 10.226.255.6
      routes:
        config:
          - destination: 0.0.0.0/0
            next-hop-address: 10.226.224.1
            next-hop-interface: ens5f1
            table-id: 254
  - hostname: master02.ocp01.pln.spirenteng.com
    role: master
    rootDeviceHints:
      deviceName: "/dev/sda"
    interfaces:
      - name: ens5f1
        macAddress: "3C:FD:FE:E1:47:25"
    networkConfig:
      interfaces:
        - name: ens5f1
          type: ethernet
          state: up
          mac-address: "3C:FD:FE:E1:47:25"
          ipv4:
            enabled: true
            address:
              - ip: 10.226.224.35
                prefix-length: 22
            dhcp: false
          ipv6: 
            enabled: true
            dhcp: true
      dns-resolver:
        config:
          server:
            - 10.226.255.5
            - 10.226.255.6
      routes:
        config:
          - destination: 0.0.0.0/0
            next-hop-address: 10.226.224.1
            next-hop-interface: ens5f1
            table-id: 254
  - hostname: master03.ocp01.pln.spirenteng.com
    role: master
    rootDeviceHints:
      deviceName: "/dev/sda"
    interfaces:
      - name: ens5f1
        macAddress: "3C:FD:FE:E1:47:51"
    networkConfig:
      interfaces:
        - name: ens5f1
          type: ethernet
          state: up
          mac-address: "3C:FD:FE:E1:47:51"
          ipv4:
            enabled: true
            address:
              - ip: 10.226.224.36
                prefix-length: 22
            dhcp: false
          ipv6: 
            enabled: true
            dhcp: true
      dns-resolver:
        config:
          server:
            - 10.226.255.5
            - 10.226.255.6
      routes:
        config:
          - destination: 0.0.0.0/0
            next-hop-address: 10.226.224.1
            next-hop-interface: ens5f1
            table-id: 254
