apiVersion: v1
baseDomain: pln.spirenteng.com
compute:
  - architecture: amd64
    hyperthreading: Enabled
    name: worker
    replicas: 0
controlPlane:
  architecture: amd64
  hyperthreading: Enabled
  name: master
  replicas: 3
metadata:
  name: ocp01
networking:
  clusterNetwork:
    - cidr: 172.16.0.0/16
      hostPrefix: 22
  machineNetwork:
    - cidr: 10.226.224.0/22
  networkType: OVNKubernetes
  serviceNetwork:
    - 172.30.0.0/16
platform:
  none: {}
fips: false
pullSecret: '{"auths":{"registry.ocp01.pln.spirenteng.com:8443":{"auth":"b3BlbnNoaWZ0OnNwaXJlbnQxMjM0NQ=="}}}'
sshKey: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCwwt+Sb0sAkQIWqIgWzzrKhUHRA3ToT8ec7PmowkG8un/doSou21Nv/N7Ii3ymwm/oI8y318tawr+r9/sDT5bpIf/ZljJRNRXYGJeKl1fDJqwIzBsYpKFDIq0OaoVKkKAz31duiQJvju2zRjZ1gg70nuoTbaS9MUItdBC7FJ0K4cm3A97w3neO5yT488/MtOpdm972jWQsI+DNJrC4xOIjqRLSP+NmnPdagQ/GRrCyV4CdzpKDcF7e7ecsdoj1k9RHx8K8tcuf77z6xVn4nLg3aZGyCnVoAo1sx/VdPLb1oThvW93dti7S4gOtzUYyDleJrx7XoY9CVd2Y3QtwExnEkeJSAfmO7xCcGYooLA6weeNh1CYynMhQonLdu2hxOBVe0Vr84sLhBbkqX5k0xYyR0QTQqRUbyA7E9R693+Z7q2rTXFlwUtY8sQI87RdXFMIO50f289MqIgB9uVLpUNji+qHkhO6mhQxq6NsaWfURSTga6ufYmJYTHQi1Uru+uVM= root@bastion.ocp01.pln.spirenteng.com' 
additionalTrustBundle: |
  -----BEGIN CERTIFICATE-----
  MIIECzCCAvOgAwIBAgIUI6qR7YABZBYgQ46qmg4N5tEPf5QwDQYJKoZIhvcNAQEL
  BQAwezELMAkGA1UEBhMCVVMxCzAJBgNVBAgMAlZBMREwDwYDVQQHDAhOZXcgWW9y
  azENMAsGA1UECgwEUXVheTERMA8GA1UECwwIRGl2aXNpb24xKjAoBgNVBAMMIXJl
  Z2lzdHJ5Lm9jcDAxLnBsbi5zcGlyZW50ZW5nLmNvbTAeFw0yNTA4MTIwNjIxNTNa
  Fw0yODA2MDEwNjIxNTNaMHsxCzAJBgNVBAYTAlVTMQswCQYDVQQIDAJWQTERMA8G
  A1UEBwwITmV3IFlvcmsxDTALBgNVBAoMBFF1YXkxETAPBgNVBAsMCERpdmlzaW9u
  MSowKAYDVQQDDCFyZWdpc3RyeS5vY3AwMS5wbG4uc3BpcmVudGVuZy5jb20wggEi
  MA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQC+IuFtCrwVqMCDuQuf2WkgEHzd
  GHjjt0afDsn2vLydxlwnWQKoNUJZNTWUO+1q/kT10gDx0Nq0J5NkHafpnb5H1Zfp
  O6eu86sNI8N+OoZW3lxpZcCXULyGdrSAF35qZFTTWPEbGYPLdsyRq+LwI4K0FaDa
  KfsXotvncZzgQDrtOvoWIIC0yAnqLhZ2zrLe2YA2F1/AfbrYMZzZPzXf7ey5hkQG
  /piRIcQntl3f9i8aMK19iDgTirFlOOkPwyN3ZMIDOeASlq9I/qAHPKm2av4SAfH8
  bF/jC20NGhZzdbsnX3ud/zPDx6jmUGPyYSPlPkkTBbOoHgG1KmMueoA+sbIrAgMB
  AAGjgYYwgYMwCwYDVR0PBAQDAgLkMBMGA1UdJQQMMAoGCCsGAQUFBwMBMCwGA1Ud
  EQQlMCOCIXJlZ2lzdHJ5Lm9jcDAxLnBsbi5zcGlyZW50ZW5nLmNvbTASBgNVHRMB
  Af8ECDAGAQH/AgEBMB0GA1UdDgQWBBR36HMJ84OBUEdyJ5zvGi1lc2tc/DANBgkq
  hkiG9w0BAQsFAAOCAQEAijtXOWSJ/NbM5ZpshL3dQ1KjpIKT3Hqz/sT7FEgcbml3
  uxmIizsXMwV0aOSz0uVJ0WM9NANbFhaYDax4WRACL74rqSs0BnUDBZo2knNoEPGV
  uEFQ1UaLOZXt1ctbsPScRu6eOh6Z0IE/kGf+2IGw+POcS1WyrHTy6Oxea9wfVKPB
  RW7I5MoV8nA0dT8AJwzWxe6Ou23NrSt4Pdhlgp08rp5JR40EpcMaXmKQ/6CFkfBP
  k1fRIW32mqefC1Jfjpe7PUkyLUL3ZNeF2Rn4p7wIkLph1mHFH8rprJ4YQE67QQvh
  JMP5f0Ym1m5Z4OV3qvklJN+qjjQWdj+mZzwtl8DBeQ==
  -----END CERTIFICATE-----
imageContentSources:
- mirrors:
  - registry.ocp01.pln.spirenteng.com:8443/openshift/release-images
  source: quay.io/openshift-release-dev/ocp-release
- mirrors: 
  - registry.ocp01.pln.spirenteng.com:8443/openshift/release
  source: quay.io/openshift-release-dev/ocp-v4.0-art-dev
